apiVersion: 1

prune: true

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: prometheus
    orgId: 1
  - name: prometheus-1
    orgId: 1

datasources:
  - name: Prometheus Monitoring
    uid: prometheus-main
    type: prometheus
    access: proxy
    url: http://monitoring-prometheus:9090
    isDefault: true
    editable: false
